-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
        exclude: blog/migrations
        args: [--max-line-length=120]
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: f464d46
    hooks:
    -   id: pep257

-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 3e5968a57a3720a490ff23b8c1a15d874bbd97fc
    hooks:
    -   id: remove-tabs
